Extend the proposal to contain two methods
rmrk-team/SoubloundEIP pull request #4
Opened 2023-04-28 10:23 UTC by ThunderDeliverer

The proposal was extended to contain two methods, one minimal and one extended, to cover a variety of use cases.
The proposal was renamed to reflect the changes.
The method was also renamed `isTransferable` from `isNonTransferable`.

2023-04-28 15:09 UTC, steven2308 requested changes
Looking good, just some minor requests.

2023-04-28 15:09 UTC, steven2308 commented on README.md
> +description: A minimal interface for Transferable Non-Fungible Tokens extension allowing for tokens to be transferable or non-transferable.
How  about:
```suggestion
description: A minimal extension to identify Transferability on Non-Fungible Tokens.
```

2023-04-28 15:09 UTC, steven2308 commented on README.md
> +The Minimalistic Transferable interface for Non-Fungible Tokens standard extends [ERC-721](./eip-721.md) by introducing the ability to identify whether an NFTs can be transfered or not.
```suggestion
The Minimalistic Transferable interface for Non-Fungible Tokens standard extends [ERC-721](./eip-721.md) by introducing the ability to identify whether NFTs can be transferred or not.
```

2023-04-28 15:09 UTC, steven2308 commented on README.md
> +     * @dev If the tokenId does not exist, this method MUST revert execution
I'd add this to the other one as well

2023-04-28 15:09 UTC, steven2308 commented on README.md
> +   One could argue that since the core of this proposal is to only prevent ERC-721 tokens to be transferred, this could be done by overriding the transfer function. While this is true, the only way t
Can we mention something about UX?

2023-04-28 15:09 UTC, steven2308 commented on README.md
> +   Both methods defined in this proposal address the same issue, but in different ways. The first method is used to check whether the token is transferable or notin general, while the second method i
```suggestion
   Both methods defined in this proposal address the same issue, but in different ways. The first method is used to check whether the token is transferable or not in general, while the second method is used to check whether the token is conditionally transferable or not based on the source and destination addresses. The second method is useful in cases where the transferability of the token is dependent on the source and destination addresses.
```

2023-04-28 15:34 UTC, ThunderDeliverer commented on assets/contracts/mocks/ERC721NonTransferableMock.sol
> +    function isTransferable(uint256 tokenId, address from, address to) public view returns (bool) {
This would not allow the exception for mint and burn here :/

2023-04-28 15:36 UTC, ThunderDeliverer commented on README.md
> +   One could argue that since the core of this proposal is to only prevent ERC-721 tokens to be transferred, this could be done by overriding the transfer function. While this is true, the only way t
Good call! I'll add it in the evening!

2023-04-28 19:28 UTC, steven2308 commented on assets/contracts/mocks/ERC721NonTransferableMock.sol
> +    function isTransferable(uint256 tokenId, address from, address to) public view returns (bool) {
We had this in the original version and it was no issue. The before token hook checks if it's mint/burn before checking if it's transferable.
If I query for a token which doesn't exist it should def revert.

2023-04-28 19:28 UTC, steven2308 commented on README.md
> +The Minimalistic Transferable interface for Non-Fungible Tokens standard extends [ERC-721](./eip-721.md) by introducing the ability to identify whether an NFTs can be transfered or not.
No issues. I just wanted to fix singular article with plural noun.

2023-05-01 07:31 UTC, ThunderDeliverer commented on assets/contracts/mocks/ERC721NonTransferableMock.sol
> +    function isTransferable(uint256 tokenId, address from, address to) public view returns (bool) {
The way it is currently implemented, it is used to validate that the tokens can only be minted or burned. This means that `_requireMited(tokenId)` would cause an unexpected revert. I have an idea on how to rectify that without adding any deliberate logic (I don't want to make the EIP example too elaborate 😅 )

2023-05-01 08:28 UTC, ThunderDeliverer commented on README.md
> +     * @dev If the tokenId does not exist, this method MUST revert execution
Which one? Both `isTransferable` functions have these `@dev` tags.

2023-05-01 13:17 UTC, steven2308 reviewed
Big why? pending :sweat_smile:

2023-05-01 13:17 UTC, steven2308 commented on assets/contracts/mocks/ERC721NonTransferableMock.sol
> +            return true;
Why??

2023-05-01 13:29 UTC, ThunderDeliverer commented on assets/contracts/mocks/ERC721NonTransferableMock.sol
> +            return true;
I wanted to add some logic here, not just leave it blank 😅

2023-05-01 13:41 UTC, merged